package io.github.moronigranja.maliprobe

import android.content.res.AssetManager
import android.opengl.EGL14
import android.opengl.EGLConfig
import android.opengl.EGLContext
import android.opengl.EGLDisplay
import android.opengl.EGLSurface
import android.opengl.GLES20
import android.opengl.GLES30
import android.util.Log
import androidx.test.ext.junit.runners.AndroidJUnit4
import androidx.test.platform.app.InstrumentationRegistry
import org.junit.Test
import org.junit.runner.RunWith

/**
 * Compiles the game's own shader text on a device's GL front end — the question the port's gate asks
 * from inside a WebView, asked here from a plain app: an **offscreen EGL context** is served by the
 * platform's *native* GL driver unless the package is opted into ANGLE (`Settings.Global`
 * `angle_gl_driver_selection_pkgs` / `…_values`), which is the path the Mali reports are about.
 *
 * Every case is one fragment shader, compiled, with one line per case in logcat under [TAG]:
 *
 * ```
 * PROBE <path> compile=<0|1> link=<0|1|-> log=<the driver's first line>
 * ```
 *
 * `link` is asked only of the `shapes/` cases — those are the port's own gate, and one of them
 * declares a varying so it needs a matching vertex shader. The `files/` and `variants/` cases are the
 * game's whole fragment shaders: the engine links them with their real `.vert`, which a probe without
 * the game cannot, so for those the compile is the question (the Mali failure the port fixes is a
 * *compile* failure: `S0032`).
 *
 * Nothing is asserted — this is a measuring instrument for a device farm — and the run ends with a
 * `SUMMARY` line, so a remote run is read from its log. The cases are the game's own bytes (expanded
 * the engine's way) and the port's edits to them, generated by `make-cases.py` and never committed.
 */
@RunWith(AndroidJUnit4::class)
class ShaderProbeTest {

    @Test
    fun compileEveryCase() {
        val assets = InstrumentationRegistry.getInstrumentation().context.assets
        val egl = Egl()
        try {
            egl.makeCurrent()
            Log.i(TAG, "gl vendor=${glString(GLES20.GL_VENDOR)}")
            Log.i(TAG, "gl renderer=${glString(GLES20.GL_RENDERER)}")
            Log.i(TAG, "gl version=${glString(GLES20.GL_VERSION)}")
            Log.i(TAG, "gl glsl=${glString(GLES20.GL_SHADING_LANGUAGE_VERSION)}")

            val cases = read(assets, INDEX).lines()
                .map { it.trim() }
                .filter { it.isNotEmpty() && !it.startsWith("#") }
            Log.i(TAG, "cases=${cases.size}")
            if (cases.isEmpty()) {
                Log.w(TAG, "no cases in $INDEX: the test APK was built without them")
                return
            }

            var compiled = 0
            val refused = mutableListOf<String>()
            val unlinked = mutableListOf<String>()
            for (path in cases) {
                val result = probe(path, read(assets, path))
                if (result.compiled) compiled++ else refused.add(path)
                if (result.linked == false) unlinked.add(path)
                Log.i(TAG, "PROBE $path compile=${yn(result.compiled)} " +
                    "link=${result.linked?.let { yn(it) } ?: "-"} log=${result.message.ifEmpty { "-" }}")
            }
            Log.i(TAG, "SUMMARY cases=${cases.size} compiled=$compiled refused=${refused.size} unlinked=${unlinked.size}")
            if (refused.isNotEmpty()) Log.i(TAG, "SUMMARY refused=${refused.joinToString(",")}")
            if (unlinked.isNotEmpty()) Log.i(TAG, "SUMMARY unlinked=${unlinked.joinToString(",")}")
        } catch (e: Throwable) {
            Log.e(TAG, "probe failed: ${e.javaClass.simpleName}: ${e.message}")
            throw e
        } finally {
            egl.release()
        }
    }

    /** One case: compile it, and link it where a matching vertex shader exists (see the class doc). */
    private fun probe(path: String, fragment: String): Result {
        val pixel = makeShader(GLES30.GL_FRAGMENT_SHADER, fragment)
        val compiled = status(pixel, GLES20.GL_COMPILE_STATUS)
        var message = if (compiled) "" else firstLine(GLES20.glGetShaderInfoLog(pixel))
        var linked: Boolean? = null
        if (path.startsWith(SHAPES_PREFIX)) {
            val vertex = makeShader(GLES30.GL_VERTEX_SHADER, vertexFor(path))
            val program = GLES20.glCreateProgram()
            GLES20.glAttachShader(program, vertex)
            GLES20.glAttachShader(program, pixel)
            GLES20.glLinkProgram(program)
            linked = status(program, GLES20.GL_LINK_STATUS)
            if (linked == false && message.isEmpty()) message = firstLine(GLES20.glGetProgramInfoLog(program))
            GLES20.glDeleteProgram(program)
            GLES20.glDeleteShader(vertex)
        }
        GLES20.glDeleteShader(pixel)
        return Result(compiled, linked, message)
    }

    private fun makeShader(type: Int, source: String): Int {
        val shader = GLES20.glCreateShader(type)
        GLES20.glShaderSource(shader, source)
        GLES20.glCompileShader(shader)
        return shader
    }

    private fun status(id: Int, which: Int): Boolean {
        val out = IntArray(1)
        if (which == GLES20.GL_COMPILE_STATUS) GLES20.glGetShaderiv(id, which, out, 0)
        else GLES20.glGetProgramiv(id, which, out, 0)
        return out[0] != 0
    }

    private fun firstLine(log: String?): String =
        (log ?: "").split('\n').firstOrNull { it.trim().isNotEmpty() }?.trim()?.take(180) ?: ""

    private fun glString(name: Int): String = GLES20.glGetString(name) ?: "?"

    private fun read(assets: AssetManager, path: String): String =
        assets.open(path).use { it.readBytes().toString(Charsets.UTF_8) }

    private fun yn(value: Boolean) = if (value) 1 else 0

    private fun vertexFor(path: String): String =
        if (path.contains("in-out")) VERTEX_FLOW else VERTEX

    private data class Result(val compiled: Boolean, val linked: Boolean?, val message: String)

    /**
     * An offscreen ES 3 context: a pbuffer and a context, on whichever GL driver the platform gives
     * this package. No window and no Activity, so a device farm can run it unattended.
     */
    private class Egl {
        private lateinit var display: EGLDisplay
        private lateinit var context: EGLContext
        private lateinit var surface: EGLSurface

        fun makeCurrent() {
            display = EGL14.eglGetDisplay(EGL14.EGL_DEFAULT_DISPLAY)
            check(display != EGL14.EGL_NO_DISPLAY) { "no EGL display" }
            val version = IntArray(2)
            check(EGL14.eglInitialize(display, version, 0, version, 1)) { "eglInitialize failed" }
            val config = chooseConfig()
            val contextAttribs = intArrayOf(EGL14.EGL_CONTEXT_CLIENT_VERSION, 3, EGL14.EGL_NONE)
            context = EGL14.eglCreateContext(display, config, EGL14.EGL_NO_CONTEXT, contextAttribs, 0)
            check(context != EGL14.EGL_NO_CONTEXT) { "no EGL context" }
            val surfaceAttribs = intArrayOf(EGL14.EGL_WIDTH, 64, EGL14.EGL_HEIGHT, 64, EGL14.EGL_NONE)
            surface = EGL14.eglCreatePbufferSurface(display, config, surfaceAttribs, 0)
            check(surface != EGL14.EGL_NO_SURFACE) { "no EGL pbuffer surface" }
            check(EGL14.eglMakeCurrent(display, surface, surface, context)) { "eglMakeCurrent failed" }
        }

        private fun chooseConfig(): EGLConfig {
            val attribs = intArrayOf(
                EGL14.EGL_RENDERABLE_TYPE, EGL_OPENGL_ES3_BIT,
                EGL14.EGL_SURFACE_TYPE, EGL14.EGL_PBUFFER_BIT,
                EGL14.EGL_RED_SIZE, 8, EGL14.EGL_GREEN_SIZE, 8, EGL14.EGL_BLUE_SIZE, 8,
                EGL14.EGL_NONE,
            )
            val configs = arrayOfNulls<EGLConfig>(1)
            val count = IntArray(1)
            check(EGL14.eglChooseConfig(display, attribs, 0, configs, 0, 1, count, 0) && count[0] > 0) {
                "no EGL config for an ES3 pbuffer"
            }
            return configs[0]!!
        }

        fun release() {
            EGL14.eglMakeCurrent(display, EGL14.EGL_NO_SURFACE, EGL14.EGL_NO_SURFACE, EGL14.EGL_NO_CONTEXT)
            if (::surface.isInitialized) EGL14.eglDestroySurface(display, surface)
            if (::context.isInitialized) EGL14.eglDestroyContext(display, context)
            if (::display.isInitialized) EGL14.eglTerminate(display)
        }
    }

    private companion object {
        const val TAG = "MaliProbe"
        const val INDEX = "index.txt"
        const val SHAPES_PREFIX = "shapes/"

        /** `EGL_OPENGL_ES3_BIT_KHR`: not in the `EGL14` constants. */
        const val EGL_OPENGL_ES3_BIT = 0x40

        val VERTEX = """
            #version 300 es
            precision highp float;
            void main() { gl_Position = vec4(0.0); }
        """.trimIndent() + "\n"

        /** The game's own vertex spelling for the varying the `in-out` shape declares. */
        val VERTEX_FLOW = """
            #version 300 es
            precision highp float;
            flat out vec2 v_flowDirs[4];
            void main() {
                for (int i = 0; i < 4; i++) v_flowDirs[i] = vec2(0.0);
                gl_Position = vec4(0.0);
            }
        """.trimIndent() + "\n"
    }
}
